phst-randomizer/ph-randomizer

- .github/workflows/test.yml
The most recent release seems to have broken downloads on windows.
> Pin `gdown` in CI

- .github/workflows/test.yml
- base/src/main.asm
- base/src/spawn_custom_freestanding_item.c
This hijacks the freestanding key code to also support spawning arbitrary items using our custom RUPY NPC.
> Spawn any item as freestanding (not just keys)

- .github/workflows/test.yml
Switch back to latest version of gdown CLI now that it's fixed on windows.
> Unpin google drive downloader

- .github/workflows/test.yml
This brings the total time required for CI tests to run from ~15 minutes to ~5 minutes.
> Cache Docker image builds

- base/src/main.asm
> Add a new bank of free space to `main.asm`

- shuffler/parser.py
- shuffler/shuffler.py
Some improvements I've made since #55
> Tweaks to shuffler

- tests/README.md
Adds more info about the testing setup to `tests/README.md`
> Update README for tests

- shuffler/auxiliary/SW Sea/Mercay Island/Mercay.json
Adds some chest locations that were missing before.
> Add some missing info to Mercay aux data

- patcher/util.py
- shuffler/aux-schema.json
- shuffler/auxiliary/SW Sea/Mercay Island/Mercay.json
- shuffler/auxiliary/SW Sea/Mercay Island/MercayGrotto.json
- shuffler/shuffler.py
The branch name is misleading, this doesn't actually finish the mercay aux data :p
> More Mercay aux data, fix shuffler bug

- shuffler/shuffler.py
This makes the shuffler CLI output easier to feed directly into the parser CLI.
> Improve output for shuffler CLI

- patcher/location_types/island_shop.py
> Fix shop gem models

- CONTRIBUTING.md
- DEVELOPMENT.md
Adds `DEVELOPMENT.md` and `CONTRIBUTING.md` files.
> Add developer documentation

- README.md
It's not immediately apparent to someone coming in blind to the repo that the randomizer isn't functional yet.
> Update readme with current status of things

- .github/workflows/build-test-release.yml
The crashing bug was fixed upstream.
> uncomment pip upgrade steps

- .github/workflows/build-test-release.yml
- patcher/_util.py
- randomizer.py
- randomizer.spec
- setup.py
Automatically applies the base patch in the patcher prior to patching ROM with randomized aux data from the shuffler.
> Apply base patch in patcher

- setup.py
- shuffler/_parser.py
- tests/test_shuffler.py
- tox.ini
> Parser for logic edge expressions

- shuffler/auxiliary/NW Sea/Isle of Gust/GustIsle.wip-json
- shuffler/auxiliary/NW Sea/Zauz Island/Zauz.wip-json
- shuffler/auxiliary/SW Sea/Spirit Isle/SpiritIsle.wip-json
- shuffler/auxiliary/Sea.wip-json
Some of the logic contained comments, which messed up the logic_to_aux script. #120 contains the changes to the logic_to_aux script needed to properly parse comments.
> Fix mangled auxiliary stubs

- shuffler/_parser.py
- shuffler/main.py
> Switch shuffler to assumed fill

- shuffler/auxiliary/Sea.json
This isn't complete, but should be enough for the time being to at least make the shuffler work
> Start of sea aux data

- shuffler/logic/NW Sea/Isle of Gust/GustIsle.logic
> Fix typo in logic

- patcher/_items.py
- shuffler/auxiliary/NW Sea/Uncharted Island/Uncharted.json
- shuffler/logic/NW Sea/Uncharted Island/Uncharted.logic
> Logic + aux data for uncharted island

- .github/workflows/build-test-release.yml
- renovate.json
> Fix Renovate automerging

- shuffler/auxiliary/Dungeons/Courage Temple/CourageTemple.wip-json
- shuffler/auxiliary/Dungeons/Courage Temple/CraykBossRoom.wip-json
- shuffler/auxiliary/Dungeons/Fire Temple/BlaazBossRoom.wip-json
- shuffler/auxiliary/Dungeons/Fire Temple/FireTemple.wip-json
- shuffler/auxiliary/Dungeons/Ghost Ship/GhostShip.wip-json
- shuffler/auxiliary/Dungeons/Goron Temple/DongorongoBossRoom.wip-json
- shuffler/auxiliary/Dungeons/Goron Temple/GoronTemple.wip-json
- shuffler/auxiliary/Dungeons/Ice Temple/GleeokBossRoom.wip-json
- shuffler/auxiliary/Dungeons/Ice Temple/IceTemple.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB0.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB1.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB2.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB3.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB3ChartRoom.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB4.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB5.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB6.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Dungeon/TempleOfTheOceanKingB6SunMapRoom.wip-json
- shuffler/auxiliary/Dungeons/ToTOK/Lobby/TempleOfTheOceanKingLobby.wip-json
- shuffler/auxiliary/NE Sea/ManOfSmilesBoat/ManOfSmilesBoat.wip-json
- shuffler/auxiliary/NW Sea/Isle of Gust/GustIsle.wip-json
- shuffler/auxiliary/SE Sea/Dee Ess Island/DSIsland.wip-json
- shuffler/auxiliary/SE Sea/Goron Island/Goron.wip-json
- shuffler/auxiliary/SE Sea/Harrow Island/Harrow.wip-json
- shuffler/auxiliary/SE Sea/HoHoBoat/HoHoBoat.wip-json
- shuffler/auxiliary/SE Sea/Isle of Frost/FrostIsle.wip-json
- shuffler/auxiliary/SW Sea/Isle of Ember/Ember.wip-json
- shuffler/auxiliary/SW Sea/Molida Island/Molida.wip-json
- shuffler/auxiliary/SW Sea/Spirit Isle/SpiritIsle.wip-json
- shuffler/logic_to_aux.py
Simplifies code using some `pathlib` shortcuts and also ensure the `name` field appears first in each `room` object.
> logic_to_aux script improvements

- shuffler/auxiliary/Dungeons/Wind Temple/WindTemple.json
- shuffler/logic/Dungeons/Wind Temple/WindTemple.logic
> Wind temple logic + aux data

- shuffler/aux_models.py
- shuffler/graphviz.py
- shuffler/logic.py
There's probably some bugs/edge cases missing here, but support for `state`/`gain`/`lose` is needed before the shuffler can be run on any dungeons besides Mercay Grotto, so I'm merging this as-is before starting that.
> Support keys/locked doors in shuffler

- setup.cfg
- shuffler/logic.py
- tests/test_shuffler.py
Changes some data structures used during shuffling to ensure that given a seed X, the randomizer will return the exact same result every time it's run with that seed.
> Fix shuffler seeds

- .github/workflows/build-test-release.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update deprecated Actions format

- patcher/__init__.py
- patcher/_util.py
- patcher/main.py
- randomizer.py
- Make base patch application actually work correctly
- Move around some functions
- Add some logging statements for missing aux data
> Clean up patcher

- ph_rando/shuffler/logic.py
This should no longer be needed now that the shuffler is more memory-efficient
> Remove recursion limit increase

- base/Dockerfile
- base/Makefile
- base/fix_y9.py
> Drop dependency on `fixy9.exe`

- ph_rando/shuffler/logic/Dungeons/Courage Temple/CourageTemple.logic
- ph_rando/shuffler/logic/Dungeons/Fire Temple/FireTemple.logic
- ph_rando/shuffler/logic/Dungeons/Ghost Ship/Dungeon/B1.logic
- ph_rando/shuffler/logic/Dungeons/Ice Temple/Dungeon/B1.logic
- ph_rando/shuffler/logic/Dungeons/Ice Temple/Dungeon/B2.logic
- ph_rando/shuffler/logic/Dungeons/Ice Temple/Dungeon/F1.logic
- ph_rando/shuffler/logic/Dungeons/Ice Temple/Dungeon/F3.logic
- ph_rando/shuffler/logic/Dungeons/Mutoh Temple/MutohTemple.logic
- ph_rando/shuffler/logic/Dungeons/ToTOK/B2/B2.logic
- ph_rando/shuffler/logic/Dungeons/ToTOK/B8/B8.logic
- ph_rando/shuffler/logic/Dungeons/ToTOK/B9/B9.logic
> Feature branch for `lose` descriptor conversion

- base/requirements.txt
Reverts phst-randomizer/ph-randomizer#432
> Revert "Bump pillow from 10.0.1 to 10.2.0 in /base"

- ph_rando/shuffler/_spoiler_log.py
- ph_rando/shuffler/main.py
- ph_rando/ui/cli.py
- ph_rando/ui/gui.py
- scripts/generate_from_spoiler_log.py
Includes settings in spoiler log
> Save settings to spoiler log

- .github/workflows/build-test-release.yml
Reverts phst-randomizer/ph-randomizer#451
> Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"

- tests/desmume/test_chest_items.py
- tests/desmume/test_dig_spot_items.py
- tests/desmume/test_salvage_items.py
- tests/desmume/test_shop_items.py
> Clean up pytest fixture/parameterization

- base/code/_island_shop_files.asm
- base/code/main.asm
- ph_rando/patcher/_util.py
Issue https://github.com/phst-randomizer/ph-randomizer/issues/10
> Feature/Make Beedle Shop items randomizable
