.github/workflows/test.yml

Adds CI steps to create a BPS patch based on the patched "base rom" and saves it as a build artifact.

Build BPS base patch in CI

---

base/src/extend_RUPY_npc.c
base/src/main.asm

The other half of this would be to hook into the roll-into-tree drop/dig spot functions to properly set `rupy_type` based on some metadata in the ZMB entry.

Extend `RUPY` NPC to enable it to drop any item in the game

---

tests/README.md
tests/conftest.py

Cleans up some of the code infrastructure around the `py-desmume` tests. Most notably, I've extended the `py-desmume` test fixture to support loading .dsv files during individual test setup.
I was going to wait until we actually had tests that made use of these new features, but I've had it laying around long enough that I'd rather get it in now before too much changes.

Improve testing infrastructure

---

base/Dockerfile
setup.py

The recent 4.0.0 release introduced breaking changes to the `color` and `graphics2D` modules, which broke the `title_screen.py` script. The ndspy devs mention in the [release notes](https://github.com/RoadrunnerWMC/ndspy/releases/tag/v4.0.0) that the `ndspy.color` module is still unstable and may be reverted or experience more breaking changes, so in that case i think we'd better just pin it to the version we've been using instead of trying to keep up with API changes

Pin ndspy to working version

---

base/src/_island_shop_files.asm
base/src/main.asm

This relocates the "randomizable" shop item models to a free area in arm9.bin. Each entry is allocated enough space to fit the longest possible NSBMD filename, so we can randomize these to any item without causing an overflow if the new item's filename is longer than the old one's.

Relocate item shop model names

---

patcher/example.py
patcher/location_types/__init__.py
patcher/location_types/event.py
patcher/location_types/island_shop.py
patcher/location_types/map_object.py
patcher/settings.py
setup.py

Brings in some code from `ph_utils` + some new code for setting item locations. Also includes an example script to demonstrate usage, mostly for documentation purposes.
Note, I've also switched to using `zed` over `zdspy` for ZMB editing, as I've found it to be much cleaner and easier to extend/modify.

Initial scaffolding for patcher

---

base/src/main.asm
patcher/example.py
patcher/location_types/__init__.py
patcher/location_types/dig_spot.py

Closes #12 
There's a function in the game code that restricts which items can be spawned via dig spots; this PR patches it so any item id can be spawned. These items use the hacked RUPY actor from #6.

Randomize shovel dig spots

---

base/src/set_initial_flags.c
base/src/spawn_custom_freestanding_item.c

These optimizations cut down the sizes of some of the compiled C binaries. This won't resolve #31, but it should provide enough free space for #16 to at least build properly.

Optimize C code to decrease size of compiled binaries

---

patcher/example.py
patcher/locations.py

`example.py` is supposed to be a temporary placeholder until we have some sort of CLI/user-facing interface to the patcher. So, I've moved the locations list out of it and into its own file.

Move item locations to their own file

---

base/src/_island_shop_files.asm
base/src/fixed_random_treasure_in_shop.c
base/src/main.asm
patcher/location_types/island_shop.py
patcher/locations.py

This PR
- It's patched to always be the Pink Coral, no matter what the NDS clock date is. Of course, this item can then be changed as usual with the patcher.
- The random treasure item handles the spawning of its NSBMD model very differently than the "regular" shop items.

Randomize random treasure shop item

---

patcher/location_types/map_object.py
patcher/locations.py

There's a bunch of custom code hooks in place in the base ROM patch to allow these types of locations to be randomized, but I neglected to support it in the patcher when I implemented the `MapObjectLocation` class.

Support roll-into-tree items in the patcher

---

base/src/main.asm
base/src/progressive_sword_check.c

Closes #18 
With these changes, the oshus sword item will check if the player already has it, and if so give them the phantom sword instead.

Progressive sword

---

.github/workflows/test.yml

The CI step that runs on Windows is currently failing because a new release of pip occurred, and it's attempting to run the update command with elevated permissions.

Fix CI failure

---

setup.py
shuffler/parser.py
shuffler/shuffler.py

Closes #55 
There's two parts to this PR -
`parser.py` contains code for parsing the `.logic` files into Python objects so the shuffler can use them.
`shuffler.py` contains code to use the parsed `.logic` files + the aux data to generate randomized aux data for the patcher.
A few things -
- The `.logic` parser doesn't support custom descriptors yet. So stuff like `mail` or `enemy` that we have in the logic currently won't work with this first iteration.
- The shuffler uses the random fill algorithm for generating seeds, which essentially works by continuously shuffling the items in the game completely at random. Each time a seed is generated, you use the logic to check if it's valid. If it is, the program stops and you have your seed. If it's not, it repeats the shuffling.
- We'll most …

Logic parser and initial shuffler implementation

---

shuffler/shuffler.py

This lets the `door.link` attribute link to other Areas (i.e. it can be `Area.Room.Node` instead of `Room.Node` and being limited to the current `room`)

Support linking doors to other areas in shuffler

---

base/src/_island_shop_files.asm

This was resulting in a crash whenever the quiver upgrade item was placed in a shop.

Fix incorrect shop model for quiver upgrade

---

patcher/items.py

Common treasures sold in the shop are randomized in the vanilla game. We don't want this behavior, instead we want it to be a fixed item so we can apply our own randomization.

Use fixed id for random treasure item

---

tests/conftest.py

Adds an additional shop location to test for. Hopefully helps avert something like what #70 solves from happening again

Add treasure item to tested Island Shop items

---

.github/workflows/build-test-release.yml

Adds a workflow that publishes a release whenever a tag is pushed to `main`. The tag in question is used as the version number; so to release version 0.0.1 of the randomizer, a developer would do
```
git checkout main
git tag -a 0.0.1
git push --tags
```
... which will kickoff a series of CI jobs that result in a new release being published to GitHub.

Add CI workflow for automatic release

---

.github/workflows/build-test-release.yml

The current conditions for allowing a release don't work because tags aren't associated with branches. Tags are completely separate from the notion of branches in git, so that if statement doesn't make any sense.

Fix release action

---

.github/workflows/build-test-release.yml
.gitignore
randomizer.py
randomizer.spec

This makes it so that the bundled CLI executable can actually find the logic and aux data, i.e. it will actually work now (relatively at least, it will still go into an infinite loop since there's no way to get bombs in the aux data yet)
Closes #77

Add PyInstaller spec file that bundles logic/aux data

---

randomizer.py
shuffler/main.py
tests/conftest.py
tests/test_shuffler.py

This lets the user specify a seed when running the randomizer. Two or more randomizer runs with the same seed will generate identical ROMs. I also wrote [a short test](https://github.com/phst-randomizer/ph-randomizer/pull/80/commits/8d6ba3872f94aabc3e0139f96b205f67ba9730fc#diff-98c05bb95f83319d5c321653f05648ee3f654ed7a6a9a01d1ed5cc87417f4ddeR49-R55) that verifies that this behaves as intended.
For now, the user can just specify some arbitrary string as the seed. In the future, definitely by the time we have a GUI, we can make this a bit more user friendly and do the auto-generated seed "phrases" that other randomizers like WW and TP have.

Extend shuffler + randomizer CLI to support seeds

---

base/Dockerfile
base/misc/title_screen.py
setup.py

This is a prerequisite for #22, since the `code` API functionality mentioned in that issue is only available in `ndspy` 4.0.0.

Update to `ndspy` 4.0.0

---

base/Dockerfile
base/Makefile

Addresses part of #22.
This repo https://github.com/phst-randomizer/nds-compressors should also be deleted (maybe archived? idk, I see no reason to keep it around) once there is reasonable confidence that this works.

Replace CUE `blz` utility with ndspy CLI

---

shuffler/aux_models.py
shuffler/aux_schema.json
shuffler/auxiliary/SW Sea/Cannon Island/Cannon.json
shuffler/auxiliary/SW Sea/Mercay Island/Mercay.json
shuffler/auxiliary/SW Sea/Mercay Island/MercayGrotto.json
shuffler/logic/SW Sea/Mercay Island/Mercay.logic
shuffler/main.py

Currently, we support connecting two `rooms` with `doors`/`exits`. But in order to support entrance randomizer, more info is needed. Saying that `room A` and `room B` are connected by `door C` isn't sufficient, since `room B` may have more than one door. Instead, the shuffler needs to know which `door`/`entrance` `door C` is connected to. 
The logic format actually supports this with the distinction between `entrance`/`exit`/`door`, I just didn't pick up on it until now :)

Update aux schema to support entrance randomizer

---

.github/workflows/build-test-release.yml
shuffler/aux_models.py

Pydantic's validation allows you to do even stricter checks on data than what JSON schema allows. Here, I've added a check that, for every `area`, ensures every `door` or `exit` in that `area` is present in both the aux data and logic. If there's a door in the aux data that's not in the logic (or vice versa), this will cause all sorts of test failures since these validators run whenever the aux data is parsed (so, any shuffler tests will likely fail for example), which is a good thing.
Later on, we'll likely want to disable these checks for performance reasons in actual releases. I'm not sure if pydantic allows them to be disabled, if not I guess this can be done with an environment variable.

Add validation for `doors` to `Area` model

---

shuffler/aux_models.py
shuffler/aux_schema.json

This makes it easier to handle parsing aux data in the patcher.

Make `Room.chests` default to empty list instead of `None`

---

base/src/set_initial_flags.c

This function doesn't need to be inlined.

Fix gcc compilation warnings

---

.github/workflows/build-test-release.yml
base/Dockerfile
base/Makefile

This will make it easier to integrate the base patch into the patcher.

Output a BPS patch instead of a patched ROM in base patch build toolchain

---

shuffler/logic_to_aux.py

The `logic_to_aux.py` script wasn't properly accounting for comments in .logic files. 
I just copied the comment-handling code from the logic parser. I guess it might be cleaner to refactor the logic parser so the comment-handling code can be reused by this script, but i don't think it's worth doing that for a one-off script

Account for comments in logic_to_aux script

---

patcher/main.py
randomizer.py
shuffler/_parser.py
shuffler/main.py
tests/conftest.py
tests/test_shuffler.py

Instead of accepting file paths in the `shuffle` and `parse` functions, make the caller do the parsing first. Also, eliminate the use of global variables in the logic parser.
This is a code refactor/cleanup to make implementing #119 easier.

Refactor shuffler/patcher logic and aux_data parsing

---

shuffler/aux_models.py

Adds an additional validation step for aux data that checks if the `contents` field contains a valid item.

Add additional validator for aux data chest contents

---

patcher/_items.py
shuffler/auxiliary/SW Sea/Cannon Island/Cannon.json

Treasure map names should correspond to the region/number of the salvage chests they lead to.

Fix treasure map name in aux data

---

base/src/ph.asm
base/src/ph.h

I found an implementation of `strcpy` in arm9.bin, might as well add it to our header file in case it's useful.

Add `strcpy` address to base patch code

---

setup.py
tox.ini

py-desmume had a bug fix in the latest release, but `tox` wasn't picking it up in my local environment since it still had the older version cached. This PR moves py-desmume and the other test-only dependencies to `setup.py` so their versions can be tracked and upgraded as needed.

Move test dependencies from `tox.ini` to `test` target in `setup.py`

---

.github/workflows/build-test-release.yml

As seen in #170, CI is setup incorrectly and doesn't run if a PR based on a fork is opened.

Fix CI triggers so they run on PRs from forks too

---

renovate.json

This changes the Renovate config so that any updates to `pre-commit` dependencies are automatically merged, provided that tests pass. Nothing in `.pre-commit-config.yaml` actually impacts the functionality of the randomizer application, it's all just code style/linting checks. So, it should always be safe to merge these kind of changes without human review. 
Application dependencies like Python libraries, Docker images, etc. will still require approval and manual merging by a human developer.

Auto merge `pre-commit `dependency updates

---

patcher/_items.py
shuffler/aux_models.py
shuffler/auxiliary/SW Sea/Mercay Island/Mercay.json
tests/conftest.py

Ensures that for a given `Area`, all chests in the logic are also present in the aux data (and vice-versa).

Add validator for chests

---

patcher/_util.py
shuffler/aux_models.py
shuffler/aux_schema.json
shuffler/auxiliary/NW Sea/Bannan Island/Bannan.json
shuffler/auxiliary/NW Sea/Uncharted Island/Uncharted.json
shuffler/auxiliary/NW Sea/Zauz Island/Zauz.json
shuffler/auxiliary/SW Sea/Cannon Island/Cannon.json
shuffler/auxiliary/SW Sea/Mercay Island/Mercay.json
shuffler/auxiliary/Sea.json

This is more fitting, because any BMG "event" can result in an item, not just an NPC interaction. It also makes the patcher terminology more consistent with the shuffler's.

Rename `npc` items to `event` items

---

.pre-commit-config.yaml

Allows aux data to be easily validated locally, instead of relying on CI. Also adds validator for github actions workflows, why not

Add pre-commit hook for validating aux data locally

---

setup.cfg

Hopefully this decreases the renovate bot spam.

Weaker pin requirements for dev-only dependencies

---

ph_rando/shuffler/logic.py
tests/test_logic.py

Strips out all `state` related code from the shuffler to prepare for a rewrite.

Remove state from shuffler

---

ph_rando/settings.json

Randomized sword is the only supported mode currently. This may change in the future, but for now it doesn't make sense to default to an option that doesn't work properly.

Change default sword mode to randomized sword

---

base/extract_rom.py
base/rebuild_rom.py
base/requirements.txt
pyproject.toml
scripts/dump_zmb.py

Temporary measure until https://github.com/RoadrunnerWMC/ndspy/pull/22 is merged.

Switch to `ndspy` fork

---

ph_rando/patcher/_util.py
ph_rando/shuffler/aux_models.py
ph_rando/shuffler/aux_schema.json
ph_rando/shuffler/logic/NW Sea/Bannan Island/Bannan.json
ph_rando/shuffler/logic/SE Sea/Dee Ess Island/DeeEss.json

code for giving bombchu bag for goron game is at 0x219613C

Randomize Goron Game + Salvatore Game rewards
